[
    {
        "country": "Denmark",
        "city": "Lyngby",
        "zip_code": "2800",
        "region": "",
        "collection_date": "2014-08-06",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": 12.494939804077,
        "latitude": 55.763519287109,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "Escherichia coli",
        "collected_by": "Johanne Ahrenfeldt",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "DK",
        "go_city": "Lyngby",
        "go_zip_code": "2800",
        "go_region": "Lyngby-Taarbæk Municipality",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "sample_1XX",
        "id": 5692
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-02-28",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "Test1_1_Y",
        "id": 5693
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2013-12-01",
        "isolation_source": "animal",
        "pathogenic": "yes",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "1",
        "sample_name": "Test2_1_Y",
        "id": 5694
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-01-01",
        "isolation_source": "laboratory",
        "pathogenic": "no",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "E. coli",
        "collected_by": "Testers from the outside of the Milkyway",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "2",
        "sample_name": "Test_Illumina_1_Y",
        "id": 5695
    },
    {
        "country": "Denmark",
        "city": "Lyngby",
        "zip_code": "2800",
        "region": "",
        "collection_date": "2014-08-06",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": 12.494939804077,
        "latitude": 55.763519287109,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "Escherichia coli",
        "collected_by": "Johanne Ahrenfeldt",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "DK",
        "go_city": "Lyngby",
        "go_zip_code": "2800",
        "go_region": "Lyngby-Taarbæk Municipality",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "sample_1XX",
        "id": 5696
    },
    {
        "country": "Denmark",
        "city": "Lyngby",
        "zip_code": "2800",
        "region": "",
        "collection_date": "2014-08-06",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": 12.494939804077,
        "latitude": 55.763519287109,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "Escherichia coli",
        "collected_by": "Johanne Ahrenfeldt",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "DK",
        "go_city": "Lyngby",
        "go_zip_code": "2800",
        "go_region": "Lyngby-Taarbæk Municipality",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "sample_1XX",
        "id": 5572
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2013-12-01",
        "isolation_source": "animal",
        "pathogenic": "yes",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "1",
        "sample_name": "Test2_1_Y",
        "id": 5570
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-01-01",
        "isolation_source": "laboratory",
        "pathogenic": "no",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "E. coli",
        "collected_by": "Testers from the outside of the Milkyway",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "2",
        "sample_name": "Test_Illumina_1_Y",
        "id": 5571
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-02-28",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "Test1_1_Y",
        "id": 5569
    },
    {
        "country": "Denmark",
        "city": "Lyngby",
        "zip_code": "2800",
        "region": "",
        "collection_date": "2014-08-06",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": 12.494939804077,
        "latitude": 55.763519287109,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "Escherichia coli",
        "collected_by": "Johanne Ahrenfeldt",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "DK",
        "go_city": "Lyngby",
        "go_zip_code": "2800",
        "go_region": "Lyngby-Taarbæk Municipality",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "sample_1XX",
        "id": 5568
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-08-08",
        "isolation_source": "laboratory",
        "pathogenic": "no",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "E. coli",
        "collected_by": "Testers from the outside of the Milkyway",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "Test_Illumina_1_Y",
        "id": 5567
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2013-12-01",
        "isolation_source": "animal",
        "pathogenic": "yes",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "1",
        "sample_name": "Test2_1_Y",
        "id": 5566
    },
    {
        "country": "Spain",
        "city": "Huesca",
        "zip_code": "",
        "region": "",
        "collection_date": "2014-02-28",
        "isolation_source": "human",
        "pathogenic": "unknown",
        "longitude": -0.40781000256538,
        "latitude": 42.131839752197,
        "strain": "",
        "source_note": null,
        "subtype": "",
        "organism": "unknown",
        "collected_by": "Center for Genomic Epidemiology",
        "location_note": null,
        "pathogenicity_note": null,
        "notes": null,
        "go_country": "ES",
        "go_city": "Huesca",
        "go_zip_code": "",
        "go_region": "Huesca",
        "location_uncertainty_flag": "1",
        "date_uncertainty_flag": "0",
        "sample_name": "Test1_1_Y",
        "id": 5565
    }
]
